# Generated by Django 6.0 on 2025-12-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('aniversario', models.DateField()),
                ('esta_ativo', models.BooleanField(default=True)),
                ('gerente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('PARA_GUARDAR', 'Para guardar'), ('DOADO', 'Doado'), ('PERDIDO', 'Perdido')], default='DISPONIVEL', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='api.associado')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='api.livro')),
            ],
        ),
    ]
