# Generated by Django 6.0 on 2025-12-20 00:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 0, 55, 11, 221656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['data_devolucao'], name='api_emprest_data_de_8ab5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['data_prevista'], name='api_emprest_data_pr_1fe63c_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['livro'], name='api_emprest_livro_i_931d17_idx'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['associado'], name='api_emprest_associa_5ea552_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['status'], name='api_livro_status_3aeef9_idx'),
        ),
    ]
