# Generated by Django 6.0 on 2025-12-20 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_associado_user_emprestimo_data_prevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 2, 11, 17, 439046, tzinfo=datetime.timezone.utc)),
        ),
    ]
