# Generated by Django 6.0 on 2025-12-21 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 12, 28, 0, 45, 30, 153080, tzinfo=datetime.timezone.utc)),
        ),
    ]
