# Generated by Django 6.0 on 2025-12-21 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 12, 28, 11, 46, 47, 685760, tzinfo=datetime.timezone.utc)),
        ),
    ]
