# Generated by Django 6.0 on 2025-12-23 20:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quem_devolveu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_devolvidos', to='api.associado'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quem_emprestou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_feitos', to='api.associado'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 12, 30, 20, 54, 26, 990733, tzinfo=datetime.timezone.utc)),
        ),
    ]
