# Generated by Django 6.0 on 2025-12-28 21:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_emprestimo_data_prevista_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 1, 4, 21, 52, 3, 695565, tzinfo=datetime.timezone.utc)),
        ),
    ]
