# Generated by Django 6.0 on 2026-01-01 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_associado_user_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 1, 8, 19, 10, 21, 205005, tzinfo=datetime.timezone.utc)),
        ),
    ]
