# Generated by Django 6.0.2 on 2026-02-13 12:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_emprestimo_data_prevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associado',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Associado', 'verbose_name_plural': 'Associados'},
        ),
        migrations.RemoveField(
            model_name='associado',
            name='esta_ativo',
        ),
        migrations.RemoveField(
            model_name='associado',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='associado',
            name='nome',
        ),
        migrations.AddField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='aniversario',
            field=models.DateField(help_text='Data de nascimento do associado', verbose_name='Data de aniversário'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associado', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 2, 20, 12, 23, 10, 840132, tzinfo=datetime.timezone.utc)),
        ),
    ]
