# Generated by Django 6.0.2 on 2026-02-15 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_associado_options_remove_associado_esta_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 2, 22, 20, 44, 2, 23645, tzinfo=datetime.timezone.utc)),
        ),
    ]
