# Generated by Django 6.0.2 on 2026-02-17 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 2, 24, 11, 49, 19, 366582, tzinfo=datetime.timezone.utc)),
        ),
    ]
