# Generated by Django 6.0.2 on 2026-02-18 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2026, 2, 25, 22, 42, 23, 726741, tzinfo=datetime.timezone.utc)),
        ),
    ]
