# Generated by Django 6.0.2 on 2026-02-24 13:34

import api.models.Emprestimo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default=api.models.Emprestimo.default_data_prevista),
        ),
    ]
