# Generated by Django 6.0.2 on 2026-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(default='Emprestimo.default_data_prevista'),
        ),
    ]
