# Generated by Django 6.0.3 on 2026-03-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_emprestimo_data_prevista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
